# Generated by Django 4.2.7 on 2024-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("poste", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="")),
            ],
        ),
        migrations.DeleteModel(
            name="team",
        ),
    ]
