# Generated by Django 4.2.7 on 2024-06-13 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_personnel_delete_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personnel",
            options={"ordering": ["nom"]},
        ),
    ]
