# Generated by Django 4.2.7 on 2024-06-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0003_alter_personnel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="whatsapp",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
