# Generated by Django 4.2.7 on 2024-05-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="prix",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
