# Generated by Django 4.2.7 on 2024-06-13 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_services_prix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="services",
            options={"ordering": ["nom"]},
        ),
    ]
