# Generated by Django 4.2.7 on 2024-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="paiements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("contact", models.IntegerField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("produit", models.TextField()),
                ("pays", models.CharField(max_length=100)),
                ("ville", models.CharField(max_length=100)),
                ("addresse_detaille", models.TextField()),
                ("prix", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
