# Generated by Django 4.2.7 on 2024-06-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiements",
            name="codepostal",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paiements",
            name="method",
            field=models.BooleanField(default=False),
        ),
    ]
