# Generated by Django 4.2.7 on 2024-06-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0002_paiements_codepostal_paiements_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paiements",
            name="method",
        ),
        migrations.AlterField(
            model_name="paiements",
            name="addresse_detaille",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="paiements",
            name="codepostal",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paiements",
            name="nom",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paiements",
            name="pays",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paiements",
            name="prenom",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paiements",
            name="prix",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="paiements",
            name="ville",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
