# Generated by Django 4.2.7 on 2024-06-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0003_remove_paiements_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiements",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
