# Generated by Django 4.2.7 on 2024-06-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0004_alter_paiements_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="services_paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, null=True)),
                ("prenom", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("contact", models.IntegerField(null=True)),
                ("date_service", models.CharField(max_length=100, null=True)),
                ("pays", models.CharField(max_length=100, null=True)),
                ("ville", models.CharField(max_length=100, null=True)),
                ("services", models.TextField()),
                ("prix", models.IntegerField(null=True)),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date_service"],
            },
        ),
    ]
