# Generated by Django 4.2.7 on 2024-07-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0005_services_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services_paiement",
            name="services",
            field=models.TextField(null=True),
        ),
    ]
