# Generated by Django 4.2.7 on 2024-07-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0006_alter_services_paiement_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services_paiement",
            name="services",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
