# Generated by Django 4.2.7 on 2024-07-01 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0007_alter_services_paiement_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services_paiement",
            name="email",
        ),
    ]
