# Generated by Django 4.2.7 on 2024-07-01 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0008_remove_services_paiement_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="services_paiement",
            options={"ordering": ["s_date_service"]},
        ),
        migrations.RenameField(
            model_name="services_paiement",
            old_name="contact",
            new_name="s_contact",
        ),
        migrations.RenameField(
            model_name="services_paiement",
            old_name="date_demande",
            new_name="s_date_demande",
        ),
        migrations.RenameField(
            model_name="services_paiement",
            old_name="date_service",
            new_name="s_date_service",
        ),
        migrations.RenameField(
            model_name="services_paiement",
            old_name="nom",
            new_name="s_nom",
        ),
        migrations.RenameField(
            model_name="services_paiement",
            old_name="pays",
            new_name="s_pays",
        ),
        migrations.RenameField(
            model_name="services_paiement",
            old_name="prenom",
            new_name="s_prenom",
        ),
        migrations.RenameField(
            model_name="services_paiement",
            old_name="prix",
            new_name="s_prix",
        ),
        migrations.RenameField(
            model_name="services_paiement",
            old_name="services",
            new_name="s_services",
        ),
        migrations.RenameField(
            model_name="services_paiement",
            old_name="ville",
            new_name="s_ville",
        ),
    ]
