# Generated by Django 4.2.7 on 2024-05-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenements",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
