# Generated by Django 4.2.7 on 2024-05-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0003_tutos"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutos",
            name="img",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
