# Generated by Django 4.2.7 on 2024-05-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0004_tutos_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="podcasts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("nom_animateur", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("img", models.ImageField(null=True, upload_to="")),
                ("audio", models.FileField(upload_to="")),
            ],
        ),
    ]
