# Generated by Django 4.2.7 on 2024-05-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0005_podcasts"),
    ]

    operations = [
        migrations.CreateModel(
            name="form_img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="")),
            ],
        ),
    ]
