# Generated by Django 4.2.7 on 2024-06-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0007_alter_about_options_alter_entete_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="info_adhesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("img", models.ImageField(upload_to="")),
            ],
            options={
                "ordering": ["titre"],
            },
        ),
        migrations.CreateModel(
            name="localisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pays", models.CharField(max_length=50)),
                ("ville", models.CharField(max_length=50, null=True)),
                ("quatier", models.CharField(max_length=50, null=True)),
                ("indicatione", models.TextField(null=True)),
                ("image", models.ImageField(null=True, upload_to="")),
            ],
            options={
                "ordering": ["pays"],
            },
        ),
    ]
