# Generated by Django 4.2.7 on 2024-07-05 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0008_info_adhesion_localisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcasts",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
