# Generated by Django 4.2.7 on 2024-06-13 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("avis_clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avis_clients",
            options={"ordering": ["nom"]},
        ),
    ]
