# Generated by Django 4.2.7 on 2024-05-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maladies",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
