# Generated by Django 4.2.7 on 2024-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0002_alter_maladies_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="essaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
    ]
