# Generated by Django 4.2.7 on 2024-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0003_essaie"),
    ]

    operations = [
        migrations.AddField(
            model_name="produits",
            name="prix",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
