# Generated by Django 4.2.7 on 2024-05-07 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0004_produits_prix"),
    ]

    operations = [
        migrations.DeleteModel(
            name="essaie",
        ),
    ]
