# Generated by Django 4.2.7 on 2024-05-09 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0006_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="call_number",
            new_name="phone_number",
        ),
    ]
