# Generated by Django 4.2.7 on 2024-05-29 12:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0008_alter_contact_nom_alter_contact_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="country",
            field=django_countries.fields.CountryField(default=23, max_length=2),
            preserve_default=False,
        ),
    ]
