# Generated by Django 4.2.7 on 2024-05-29 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0009_contact_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="country",
            new_name="pays",
        ),
    ]
