# Generated by Django 4.2.7 on 2024-05-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0010_rename_country_contact_pays"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="contact",
            name="numero_telephone",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
