# Generated by Django 4.2.7 on 2024-05-29 20:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0011_remove_contact_phone_number_contact_numero_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="numero_telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
