# Generated by Django 4.2.7 on 2024-05-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0012_alter_contact_numero_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="numero_telephone",
            field=models.IntegerField(),
        ),
    ]
